name: "Check for performance regressions"

on:
  pull_request:


# Env variables
env:
  benchfx_rev: max-allowed-regression

jobs:
  bench:
    name: Setup environment, prepare & run benchmarks
    runs-on: ubuntu-latest
    steps:
    - name: Checkout wasmtime
      uses: actions/checkout@v4
      with:
        submodules: true
        path: wasmtime
        fetch-depth: 0

    - name: Checkout benchfx
      uses: actions/checkout@v4
      with:
        repository: 'wasmfx/benchfx'
        ref: ${{ env.benchfx_rev }}
        submodules: true
        path: benchfx
        fetch-depth: 0

    - name: Install hyperfine
      run: cargo install hyperfine

    - name: Install other deps
      run: sudo apt-get install cmake ocaml dune menhir libmenhir-ocaml-dev

    - name: Show context info
      run: |
        echo "$GITHUB_WORKSPACE"
        ls -l "$GITHUB_WORKSPACE"
        ls -l "$GITHUB_WORKSPACE/wasmtime"
        ls -l "$GITHUB_WORKSPACE/benchfx"
        cargo --version
        rustc --version
        echo "base_ref: ${{ github.base_ref }}"
        echo "head_ref: ${{ github.head_ref }}"

   - name: Initialize benchfx
      run: ./harness.py -v setup --wasmtime-create-worktree-from-development-repo=$GITHUB_WORKSPACE/wasmtime
      working-directory: ./benchfx

    - name: Prepare benchmarks
      run: ./harness.py compare-revs --prepare-only ${{ github.base_ref }} ${{ github.head_ref }}
      working-directory: ./benchfx
