name: "Check for performance regressions"

on:
  pull_request:


# Env variables
env:
  benchfx_rev: max-allowed-regression

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        repository: 'wasmfx/benchfx'
        ref: ${{ env.benchfx_rev }}$
        submodules: true
        path: benchfx
        fetch-depth: 0
    - uses: ./.github/actions/install-rust
