name: "Check for performance regressions"

on:
  pull_request:


# Env variables
env:
  benchfx_rev: max-allowed-regression

jobs:
  setup:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout wasmtime
      uses: actions/checkout@v4
      with:
        submodules: true
        path: wasmtime
        fetch-depth: 0
    - name: Checkout benchfx
      uses: actions/checkout@v4
      with:
        repository: 'wasmfx/benchfx'
        ref: ${{ env.benchfx_rev }}
        submodules: true
        path: benchfx
        fetch-depth: 0
    - name: Install hyperfine
      run: cargo install hyperfine
    - name: Install other deps
      run: sudo apt-get install cmake ocaml dune menhir libmenhir-ocaml-dev
    - name: Show context info
      run: |
        echo "$GITHUB_WORKSPACE"
        ls -l "$GITHUB_WORKSPACE"
        ls -l "$GITHUB_WORKSPACE/wasmtime"
        ls -l "$GITHUB_WORKSPACE/benchfx"
        cargo --version
        rustc --version
    - name: Initialize benchfx
      run: ./harness.py setup --wasmtime-create-worktree-from-development-repo=$GITHUB_WORKSPACE/wasmtime

#

    # - name: Install Rust
    #   uses: ./wasmtime/.github/actions/install-rust
    #   working-directory: ./wasmtime

  # build:
  #   name: Build
  #   runs-on: ubuntu-latest
  #   needs: setup
