name: "Check for performance regressions"

on:
  pull_request:


# Env variables
env:
  benchfx_rev: max-allowed-regression

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout wasmtime
      uses: actions/checkout@v4
      with:
        submodules: true
        path: wasmtime
        fetch-depth: 0
    - name: Checkout benchfx
      uses: actions/checkout@v4
      with:
        repository: 'wasmfx/benchfx'
        ref: ${{ env.benchfx_rev }}
        submodules: true
        path: benchfx
        fetch-depth: 0
    - uses: ./wasmtime/.github/actions/install-rust
